version: "3.8"
services:
    # PHP service
    app:
        build: ./docker/php/
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network
    # MySQL database service
    db:
        image: postgres:13.5-alpine
        container_name: postgresql
        volumes:
            - ./docker/psql:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        env_file:
            - .env
        ports:
            - "5452:5432"
    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
